export const QUESTION_PROTOCOL = [
  '## Question Protocol',
  '',
  'When you need input from the user to make a decision, use the following structured format:',
  '',
  '- Ask 2-8 structured multiple-choice questions per message.',
  '- Each question must include:',
  '  - A "Decide for me" option (recommended default action).',
  '  - An "Explore options" option (ask for more details).',
  '  - Other concrete actionable options.',
  '',
  'Format:',
  '  1. Question text here?',
  '     A) Decide for me \u2014 [recommended action]',
  '     B) Explore options \u2014 [what additional info is needed]',
  '     C) [other option description]',
  '',
  'User replies with numbers/letters (e.g., "1A", "2B").',
  'Parse the selection and execute the chosen action.',
  '',
  'Example:',
  '  1. How should I organize your daily notes?',
  '     A) Decide for me \u2014 Create a /daily/YYYY/MM/DD.md structure',
  '     B) Explore options \u2014 Show me alternative structures',
  '     C) Just use a single /Journal.md file',
  '',
  '  2. Should I add frontmatter tags?',
  '     A) Decide for me \u2014 Add created/modified date and tags',
  '     B) Explore options \u2014 Ask me about specific tags to add',
  '     C) No, keep it simple',
].join('\n');
